### ISSUE TITLE
1.4.3 Changes

### ISSUE THREAD

**Issue by ryannatesmith** [acres4/foundation-documentation#2]
Find and update the 1.4 documentation to accurately reflect what is going on in 1.4.3.

**Comment by mndailey** [comment]
Please add a section or separate .md file that documents the changes from 1.3 (we never released 1.4.2 for all intents).

**Comment by ryannatesmith** [comment]
Not a lot changed from 1.3 to 1.4. The biggest changes we have made are from 1.4.2 to 1.4.3, and they are all additive with the exception of returning raw flat packets as opposed to arrays of them.

**Comment by mndailey** [comment]
I believe this is the case but all timestamps in 1.4 (starting with 1.4.3 when it deploys) should be Milli Seconds since the epoch: 1970-01-01T00:00:00.000Z
Note that our package gmi contains:

- func MSToTime(ms uint64) time.Time
- func TimeToMS(t time.Time) uint64

**Comment by ryannatesmith** [comment]
Covered both with commits [7118750](https://github.com/acres4/foundation-documentation/commit/7118750b03fe5379b09f1f3a3a4c1fb311dec1e8) and [7b434fd](https://github.com/acres4/foundation-documentation/commit/7b434fdd3bbeb3989195de24d443c6bdff22fc47).
